# Função para exibir o menu
def exibir_menu():
    print("======= MENU =======")
    print("1 - Gerar chave publica e privada")
    print("2 - Criptografar mensagem")
    print("3 - Descriptografar mensagem")
    print("4 - Exibir dicionários")
    print("5 - Baixar arquivo")
    print("6 - Upload de arquivo")
    print("7 - carregar dicionario")
    print("8 - Gerar dicionario ")
    print("9 - Criptografar com chave publica ")
    print("10 - descriptografar privada")
    print("11 - Criptografar com chave privada ")
    print("12 - descriptografar publica")
    print("0 - Sair")
    print("====================")